"""Healing actions for common development environment issues."""

from __future__ import annotations

import os
from pathlib import Path
import re
import sys

from maxpayne.core.result import CheckResult
from maxpayne.core.system import command_exists, run_command


def build_sanitized_env_example(content: str) -> str:
    """Generate a sanitized `.env.example` from `.env` contents."""
    lines: list[str] = ["# Generated by MaxPayne heal", "# Replace placeholder values before use", ""]

    for raw_line in content.splitlines():
        stripped = raw_line.strip()
        if not stripped:
            lines.append("")
            continue
        if stripped.startswith("#"):
            lines.append(raw_line)
            continue

        if "=" not in raw_line:
            continue

        key, _value = raw_line.split("=", 1)
        key = key.strip().removeprefix("export ").strip()
        if not key:
            continue

        lines.append(f"{key}=<set-me>")

    return "\n".join(lines).rstrip() + "\n"


def heal_env_files(project_dir: Path | None = None) -> CheckResult:
    root = project_dir or Path.cwd()
    env_file = root / ".env"
    env_example_file = root / ".env.example"

    if not env_file.exists():
        return CheckResult(
            name="heal.env",
            status="PASS",
            message="No .env file found. Nothing to heal.",
            suggestion="No action required.",
        )

    if env_example_file.exists():
        return CheckResult(
            name="heal.env",
            status="PASS",
            message=".env.example already exists.",
            suggestion="No action required.",
        )

    try:
        sanitized = build_sanitized_env_example(env_file.read_text(encoding="utf-8"))
        env_example_file.write_text(sanitized, encoding="utf-8")
        return CheckResult(
            name="heal.env",
            status="PASS",
            message="Generated sanitized .env.example from .env.",
            suggestion="Review placeholders and fill project-safe defaults.",
            details=str(env_example_file),
        )
    except OSError as exc:
        return CheckResult(
            name="heal.env",
            status="FAIL",
            message="Failed to generate .env.example.",
            suggestion="Check file permissions and rerun `maxpayne heal env`.",
            details=str(exc),
        )


def heal_git_config(interactive: bool = False) -> CheckResult:
    available, _ = command_exists("git", "git.exe")
    if not available:
        return CheckResult(
            name="heal.git",
            status="FAIL",
            message="git is unavailable; cannot heal git identity.",
            suggestion="Install git first, then rerun `maxpayne heal git`.",
        )

    name_res = run_command(["git", "config", "--global", "--get", "user.name"])
    email_res = run_command(["git", "config", "--global", "--get", "user.email"])

    current_name = name_res.stdout.strip() if name_res.returncode == 0 else ""
    current_email = email_res.stdout.strip() if email_res.returncode == 0 else ""

    updates: list[str] = []

    if not current_name:
        fallback_name = os.environ.get("GIT_AUTHOR_NAME", "Your Name")
        value = input("Git user.name: ").strip() if interactive else fallback_name
        set_name = run_command(["git", "config", "--global", "user.name", value])
        if set_name.returncode == 0 and not set_name.error and not set_name.timed_out:
            updates.append("user.name")
        else:
            return CheckResult(
                name="heal.git",
                status="FAIL",
                message="Failed to set git user.name.",
                suggestion='Set it manually with `git config --global user.name "Your Name"`.',
                details=set_name.stderr or set_name.error,
            )

    if not current_email:
        fallback_email = os.environ.get("GIT_AUTHOR_EMAIL", "you@example.com")
        value = input("Git user.email: ").strip() if interactive else fallback_email
        set_email = run_command(["git", "config", "--global", "user.email", value])
        if set_email.returncode == 0 and not set_email.error and not set_email.timed_out:
            updates.append("user.email")
        else:
            return CheckResult(
                name="heal.git",
                status="FAIL",
                message="Failed to set git user.email.",
                suggestion='Set it manually with `git config --global user.email "you@example.com"`.',
                details=set_email.stderr or set_email.error,
            )

    if not updates:
        return CheckResult(
            name="heal.git",
            status="PASS",
            message="Git identity already configured.",
            suggestion="No action required.",
        )

    return CheckResult(
        name="heal.git",
        status="PASS",
        message="Updated missing git identity fields.",
        suggestion="Review values with `git config --global --list`.",
        details=", ".join(updates),
    )


def heal_port(port: int, interactive: bool = False) -> CheckResult:
    try:
        import psutil
    except Exception as exc:  # pragma: no cover - dependency failure path
        return CheckResult(
            name=f"heal.port.{port}",
            status="FAIL",
            message="psutil is unavailable; cannot heal ports.",
            suggestion="Install psutil and rerun the command.",
            details=str(exc),
        )

    pids: set[int] = set()
    for connection in psutil.net_connections(kind="inet"):
        if connection.status != psutil.CONN_LISTEN or not connection.laddr:
            continue
        if connection.laddr.port == port and connection.pid:
            pids.add(connection.pid)

    if not pids:
        return CheckResult(
            name=f"heal.port.{port}",
            status="PASS",
            message=f"Port {port} is already free.",
            suggestion="No action required.",
        )

    terminated: list[str] = []
    failed: list[str] = []

    for pid in pids:
        try:
            process = psutil.Process(pid)
            process_name = process.name()
            if interactive:
                answer = input(f"Terminate PID {pid} ({process_name}) on port {port}? [y/N]: ").strip().lower()
                if answer not in {"y", "yes"}:
                    failed.append(f"{pid}:{process_name} (skipped)")
                    continue

            process.terminate()
            try:
                process.wait(timeout=2)
            except psutil.TimeoutExpired:
                process.kill()
            terminated.append(f"{pid}:{process_name}")
        except (psutil.NoSuchProcess, psutil.AccessDenied) as exc:
            failed.append(f"{pid}: {exc}")

    if failed:
        return CheckResult(
            name=f"heal.port.{port}",
            status="WARN",
            message=f"Port {port} heal completed with warnings.",
            suggestion="Close remaining processes manually and rerun diagnostics.",
            details=f"terminated={terminated or ['none']}, issues={failed}",
        )

    return CheckResult(
        name=f"heal.port.{port}",
        status="PASS",
        message=f"Freed port {port}.",
        suggestion="No action required.",
        details=", ".join(terminated),
    )


def heal_dependency(package: str) -> CheckResult:
    if not re.fullmatch(r"[A-Za-z0-9_.-]+", package):
        return CheckResult(
            name=f"heal.dependency.{package}",
            status="FAIL",
            message="Invalid package name.",
            suggestion="Provide a valid package name, e.g. `maxpayne heal dependency fastapi`.",
        )

    install = run_command([sys.executable, "-m", "pip", "install", package], timeout=120)
    succeeded = install.returncode == 0 and not install.error and not install.timed_out

    return CheckResult(
        name=f"heal.dependency.{package}",
        status="PASS" if succeeded else "FAIL",
        message=(
            f"Installed dependency: {package}."
            if succeeded
            else f"Failed to install dependency: {package}."
        ),
        suggestion=(
            "No action required." if succeeded else "Check package name/network and rerun the command."
        ),
        details=(install.stderr or install.error or install.stdout or None),
    )


def apply_default_heal(interactive: bool = False) -> list[CheckResult]:
    return [
        heal_git_config(interactive=interactive),
        heal_env_files(),
    ]
